apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -c
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: podcast-web
  name: podcast-web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: podcast-web
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -c
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: podcast-web
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ASPNETCORE_URLS
              value: http://+:80
            - name: ListenTogetherHub
              value: http://listentogether.hub/listentogether
            - name: PodcastApi__BaseAddress
              value: http://podcast.api
          image: podcastweb
          name: podcast-web
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
status: {}
