version: '3.4'

services:

  podcast.api:
    image: jeffhollan/podcastapi
    build:
      context: .
      dockerfile: src/Services/Podcasts/Podcast.API/Dockerfile
    depends_on:
      - podcast.db
      - storage
    environment:
      - ConnectionStrings__PodcastDb=Server=podcast.db;Database=Podcast;User Id=sa;Password=Pass@word
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__FeedQueue=UseDevelopmentStorage=true;DevelopmentStorageProxyUri=http://azurite
    ports:
      - "5000:80"

  podcast.updater.worker:
    image: jeffhollan/podcastupdaterworker
    build:
      context: .
      dockerfile: src/Services/Podcasts/Podcast.Updater.Worker/Dockerfile
    depends_on:
      - podcast.db
      - podcast.api
      - storage
    environment:
      - ConnectionStrings__PodcastDb=Server=podcast.db;Database=Podcast;User Id=sa;Password=Pass@word

  podcast.db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"
    volumes:
      - podcast-sqldata:/var/opt/mssql

  listentogether.hub:
    image: jeffhollan/listentogetherhub
    build:
      context: .
      dockerfile: src/Services/ListenTogether/ListenTogether.Hub/Dockerfile
    depends_on:
      - podcast.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - NetPodcastApi__BaseAddress=http://podcast.api
      - ConnectionStrings__ListenTogetherDb=Server=podcast.db;Database=ListenTogether;User Id=sa;Password=Pass@word
    ports:
      - "5001:80"

  podcast.ingestion.worker:
    image: jeffhollan/podcastingestionworker
    build:
      context: .
      dockerfile: src/Services/Podcasts/Podcast.Ingestion.Worker/Dockerfile
    depends_on:
      - podcast.db
      - storage
    environment:
      - ConnectionStrings__PodcastDb=Server=podcast.db;Database=Podcast;User Id=sa;Password=Pass@word
      - ConnectionStrings__FeedQueue=UseDevelopmentStorage=true;DevelopmentStorageProxyUri=http://azurite

  podcast.web:
    image: jeffhollan/podcastweb
    build:
      context: .
      dockerfile: src/Web/Server/Dockerfile
    depends_on:
      - podcast.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - PodcastApi__BaseAddress=http://podcast.api
      - ListenTogetherHub=http://listentogether.hub/listentogether
    ports:
      - "5002:80"

  storage:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    hostname: azurite
    ports:
      - "10000:10000"
      - "10001:10001"
volumes:
  podcast-sqldata:
    external: false
