apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -c
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: storage
  name: storage
spec:
  ports:
    - name: "10000"
      port: 10000
      targetPort: 10000
    - name: "10001"
      port: 10001
      targetPort: 10001
  selector:
    io.kompose.service: storage
status:
  loadBalancer: {}
